### ISSUE TITLE
Can't run python tests

### ISSUE THREAD

**Issue by josedlpozo** [facebook/screenshot-tests-for-android#111]
Hello! 

I am cooking a new feature and I will open a PR soon. I have some problems trying to run python tests. I have never developed python, so, forgive me if this question is very silly.

I try to run them with this command: python -m unittest discover , but it results with a import error. This is the output:

`EEEEEE
======================================================================
ERROR: test_aapt (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_aapt
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/josedelpozo/Documents/workspace/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/test_aapt.py", line 7, in <module>
    from . import aapt
ValueError: Attempted relative import in non-package

======================================================================
ERROR: test_common (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_common
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/josedelpozo/Documents/workspace/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/test_common.py", line 13, in <module>
    from . import common
ValueError: Attempted relative import in non-package

======================================================================
ERROR: test_metadata (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_metadata
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/josedelpozo/Documents/workspace/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/test_metadata.py", line 20, in <module>
    from . import metadata
ValueError: Attempted relative import in non-package

======================================================================
ERROR: test_pull_screenshots (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_pull_screenshots
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/josedelpozo/Documents/workspace/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/test_pull_screenshots.py", line 18, in <module>
    from . import pull_screenshots
ValueError: Attempted relative import in non-package

======================================================================
ERROR: test_recorder (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_recorder
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/josedelpozo/Documents/workspace/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/test_recorder.py", line 16, in <module>
    from .recorder import Recorder, VerifyError
ValueError: Attempted relative import in non-package

======================================================================
ERROR: test_simple_puller (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_simple_puller
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/josedelpozo/Documents/workspace/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/test_simple_puller.py", line 17, in <module>
    from .simple_puller import SimplePuller
ValueError: Attempted relative import in non-package

----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (errors=6)`

How can I run these tests?
 I just want to be sure that my changes don't break anything 😄 

Thank you!

**Comment by josedlpozo** [comment]
Hello! 
I have tried with the same command in an Ubuntu machine, and it works :smile: . I think that the problem was my Mac python setup.

Sorry and thank you!
