### ISSUE TITLE
Could not find build-tools

### ISSUE THREAD

**Issue by gfcut** [facebook/screenshot-tests-for-android#15]
Hi,

I can't run this gradle command on Windows: gradle recordMode screenshotTests. I always get the "TaskExecutionException: Execution failed for task ':pullScreenshots'" error
I already installed Python 2.7.1 and the Pillow library 2.1.0 and set my ANDROID_HOME variable.

Above the error there's a message saying: RuntimeError: Could not find build-tools in D:\tools\Android\sdk

Is there anything I can do, or it shouldn't suppose to work on Windows at this time?

Thanks

**Comment by tdrhq** [comment]
Thanks, this would be part of Windows support, give me some time to make this work :)

**Comment by scottkennedy** [comment]
I'm having the same issue on OS X.

```
OSError: [Errno 2] No such file or directory: '~/Library/Android/sdk/build-tools'
:app:pullScreenshots FAILED
```

```
$ ls ~/Library/Android/sdk/build-tools
23.0.1	23.0.2
$
```

I haven't had time to investigate this issue, but the directory it claims does not exist definitely exists.

**Comment by tdrhq** [comment]
@scottkennedy  can you give me the full stack?

It looks like you have '~' in your ANDROID_SDK/ANDROID_HOME, is that right?

**Comment by scottkennedy** [comment]
```
:app:pullScreenshots
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/scott.kennedy/.m2/repository/com/facebook/testing/screenshot/plugin/0.2.5/plugin-0.2.5.jar/android_screenshot_tests/pull_screenshots.py", line 258, in <module>
  File "/Users/scott.kennedy/.m2/repository/com/facebook/testing/screenshot/plugin/0.2.5/plugin-0.2.5.jar/android_screenshot_tests/pull_screenshots.py", line 238, in main
  File "/Users/scott.kennedy/.m2/repository/com/facebook/testing/screenshot/plugin/0.2.5/plugin-0.2.5.jar/android_screenshot_tests/aapt.py", line 43, in get_package
  File "/Users/scott.kennedy/.m2/repository/com/facebook/testing/screenshot/plugin/0.2.5/plugin-0.2.5.jar/android_screenshot_tests/aapt.py", line 32, in get_aapt_bin
OSError: [Errno 2] No such file or directory: '~/Library/Android/sdk/build-tools'
:app:pullScreenshots FAILED
```

FYI, the only change I have in my local copy right now is the version number.

If I change $ANDROID_SDK to be `/Users/scott.kennedy/Library/Android/sdk/`, it works fine.

**Comment by tdrhq** [comment]
@scottkennedy  okay so perhaps I need to support tilde expansion then, especially if other android tools seems to support it. Different from the original bug report though

**Comment by tdrhq** [comment]
@scottkennedy  your particular issue should be fixed in 042af6d46fc41c6e750f350597eaf2460393b63

Keeping the task open for the windows issues

**Comment by tdrhq** [comment]
got the git hash wrong: https://github.com/facebook/screenshot-tests-for-android/commit/0042af6d46fc41c6e750f350597eaf2460393b63

**Comment by tdrhq** [comment]
@gfcut Can you check if master works again? I've now added Windows support
