### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by Serecac** [facebook/screenshot-tests-for-android#159]
Hi, I'm trying to add the plugin to use its testing framework but when I try to record the screenshots I get an error the following dependencies error:

Caused by: com.android.dex.DexException: Multiple dex files define Lcom/android/dx/io/instructions/InstructionCodec$6;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
        at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)

This package (com.android.dx.*) generate duplicated files because two dependencies use it and it seems that they have different versions of it. The dependencies that use it are:

+--- com.facebook.testing.screenshot:core:0.6.0
|    +--- com.crittercism.dexmaker:dexmaker:1.4
|    \--- **com.crittercism.dexmaker:dexmaker-dx:1.4**   
+--- org.mockito:mockito-core:2.15.0
|    +--- net.bytebuddy:byte-buddy:1.7.9
|    +--- net.bytebuddy:byte-buddy-agent:1.7.9
|    \--- org.objenesis:objenesis:2.6
+--- org.mockito:mockito-android:2.15.0
|    +--- org.mockito:mockito-core:2.15.0 (*)
|    \--- net.bytebuddy:byte-buddy-android:1.7.9
|         +--- net.bytebuddy:byte-buddy:1.7.9
|         \--- com.jakewharton.android.repackaged:dalvik-dx:1
|              \--- **com.jakewharton.android.repackaged:libcore-dex:2**

I can not solve the conflict. Any ideas?
Thank you very much and a great job.

**Comment by xiphirx** [comment]
This was brought up previously: #152 and the dependency shouldn't be in the core library at all. It will be fixed in the next version. In the meantime, you should be able to exclude that crittercism dependency entirely.
