### ISSUE TITLE
python finished with non-zero exit value 1

### ISSUE THREAD

**Issue by neigaard** [facebook/screenshot-tests-for-android#206]
Hi,

I am trying to get a simple snapshot test running and I have followed the guide and created my own test runner and created this simple test:

```
@Test
    public void snapshotTest() {
        Context targetContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
        LayoutInflater layoutInflater = LayoutInflater.from(targetContext);
        View view = layoutInflater.inflate(R.layout.some_view, null, false);
        ViewHelpers.setupView(view).setExactWidthDp(300).layout();
        Screenshot.snap(view).record();
    }
```

I had it working but now it fails and I have changed nothing. This is the error I get:

```
:app:pullDebugAndroidTestScreenshots
[-m, android_screenshot_tests.pull_screenshots, --apk, /Users/dksokrne/Downloads/SpoonTest/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk, --temp-dir, /Users/dksokrne/Downloads/SpoonTest/app/build/screenshotsDebugAndroidTest]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dksokrne/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/pull_screenshots.py", line 487, in <module>
  File "/Users/dksokrne/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/pull_screenshots.py", line 458, in main
  File "/Users/dksokrne/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/aapt.py", line 43, in get_package
  File "/Users/dksokrne/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/aapt.py", line 16, in _check_output
  File "/Users/dksokrne/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/common.py", line 41, in check_output
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'/Users/dksokrne/Library/Android/sdk/build-tools/28.0.3/aapt', u'dump', u'badging', '/Users/dksokrne/Downloads/SpoonTest/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk']' returned non-zero exit status 1
:app:pullDebugAndroidTestScreenshots FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:pullDebugAndroidTestScreenshots'.
> Process 'command 'python'' finished with non-zero exit value 1
```

I am on a Mac and have python installed via brew, is there anything wrong with my python setup or how can I fix this?

P.S. Is there a forum where I can reach out for help on this tool? Stackoverflow or somewhere else?

Thank you
Søren

**Comment by xiphirx** [comment]
From your error log it seems like aapt doesn't like your apk

Try running the following:

```
/Users/dksokrne/Library/Android/sdk/build-tools/28.0.3/aapt dump badging /Users/dksokrne/Downloads/SpoonTest/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
```

To see what the actual error is here.

For help regarding this tool, the issue section here is fine for now. You may also try StackOverflow, but I'm not entirely active on it.

**Comment by neigaard** [comment]
Thank you. That gave me a clue, it was after a clean it started failed I can see now because the app was missing, and if I run connectedAndroidTest all is good again. So I have to make sure that connectedAndroidTest is run before the snapshot target?

**Comment by xiphirx** [comment]
Not necessarily, you just need to have the apk to reference so that the script can determine the proper package name, etc.
