### ISSUE TITLE
MainActivity test failed

### ISSUE THREAD

**Issue by gajanandchouhan** [facebook/screenshot-tests-for-android#212]
Hi when I am trying to run MainActivityTest through this sample it is failed and generating below crash log and also when I am  using in own sample some view are working and some shows same errors.

<failure>java.lang.RuntimeException: Unable to start activity ComponentInfo{com.facebook.testing.screenshot.example/com.facebook.testing.screenshot.sample.MainActivity}: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class android.support.design.widget.CoordinatorLayout
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class android.support.design.widget.CoordinatorLayout
Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class android.support.design.widget.CoordinatorLayout
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
at android.view.LayoutInflater.createView(LayoutInflater.java:645)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
at com.facebook.testing.screenshot.sample.MainActivity.onCreate(MainActivity.kt:42)
at android.app.Activity.performCreate(Activity.java:6679)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.support.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:667)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NoSuchFieldError: No field coordinatorLayoutStyle of type I in class Landroid/support/coreui/R$attr; or its superclasses (declaration of 'android.support.coreui.R$attr' appears in /data/app/com.facebook.testing.screenshot.example.test-1/base.apk)
at android.support.design.widget.CoordinatorLayout.&lt;init&gt;(CoordinatorLayout.java:202)
... 24 more
</failure>

Please help by provide any solution to resolve this inflate exception

**Comment by lwasyl** [comment]
Are you sure you have coordinator layout dependency added? It should be in `com.android.support:coordinatorlayout:28.0.0`. Or perhaps you're using androidx libraries already and have `androidx.coordinatorlayout:coordinatorlayout:1.0.0` then you need to update the view in xml to `androidx.coordinatorlayout.widget.CoordinatorLayout`

**Comment by xiphirx** [comment]
The sample tests have been fixed as of 0.10.0
