### ISSUE TITLE
Recording and verifying fails if multiple devices are connected

### ISSUE THREAD

**Issue by lwasyl** [facebook/screenshot-tests-for-android#213]
Since #140 is closed I wanted to raise the issue again. When multiple devices are connected, both `record...` and `verify...` tasks fail with the following stacktrace:

```
> Task :app:verifyStageDebugAndroidTestScreenshotTest FAILED
[-m, android_screenshot_tests.pull_screenshots, --apk, [redacted].apk, --temp-dir, [redacted]/screenshotsStageDebugAndroidTest, --verify, screenshots, --multiple-devices, true]
error: more than one device/emulator
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/wasyl/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/pull_screenshots.py", line 487, in <module>
  File "/Users/wasyl/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/pull_screenshots.py", line 483, in main
  File "/Users/wasyl/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/pull_screenshots.py", line 402, in pull_screenshots
  File "/Users/wasyl/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/pull_screenshots.py", line 361, in pull_filtered
  File "/Users/wasyl/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/pull_screenshots.py", line 310, in pull_metadata
  File "/Users/wasyl/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/simple_puller.py", line 44, in get_external_data_dir
  File "/Users/wasyl/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.8.0/27a0239800c59ddc144ff1aa5481b411c67a7825/plugin-0.8.0.jar/android_screenshot_tests/common.py", line 41, in check_output
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/local/share/android-sdk/platform-tools/adb', u'shell', u'echo', u'$EXTERNAL_STORAGE']' returned non-zero exit status 1
```

Does `multipleDevices = true` support recording and verifying screenshots for multiple devices simultaneously, or is it only a flag to pull screenshots into distinct directories (which only works with one device at a time)?

I could run the tests on multiple devices at a time and only pull screenshots sequentially, by setting `ANDROID_SERIAL` variable and running the pull task multiple times. But even then, `verify...` task will run and try to pull the screenshots again anyway, which fails.

**Comment by xiphirx** [comment]
I've re-opened the old task, please comment there.
