### ISSUE TITLE
0.9 breaks screenshot tests

### ISSUE THREAD

**Issue by doodla** [facebook/screenshot-tests-for-android#222]
This might be specific to us, although I don't know why. All our screenshot tests are working perfectly on `0.8`. After some pretty painful git bisect, b9ea67781085ababef8f0f71f538dfd7b53d801e is the commit which broke everything for us. I don't know enough about the internals to guess what is happening.

Our tests fail with InflateException on a custom view that we wrote.

**Comment by xiphirx** [comment]
What is the stacktrace?

**Comment by doodla** [comment]
```
    Process: com.company.debug, PID: 7262
    java.lang.RuntimeException: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class com.company.offers.ui.promowidget.PromoWidgetView
    at com.company.utils.CkLog.throwFirstExceptionIfDebug(CkLog.java:232)
    at com.company.utils.CkLog.wtf(CkLog.java:219)
    at com.company.ui.widget.recyclerview.DelegatedViewAdapterUtils.onBindViewHolder(DelegatedViewAdapterUtils.java:23)
    at com.company.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:50)
    at com.company.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:16)
    at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
    at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
    at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
    at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
    at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
    at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
    at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
    at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
    at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
    at android.view.View.measure(View.java:21783)
    at com.facebook.testing.screenshot.ViewHelpers.layoutInternal(ViewHelpers.java:79)
    at com.facebook.testing.screenshot.ViewHelpers.layout(ViewHelpers.java:68)
    at com.company.CkScreenshotTest.screenshotWithName(CkScreenshotTest.kt:77)
    ```

**Comment by xiphirx** [comment]
There is more to that stacktrace, specifically there is an underlying cause exception that bubbles up into a InflateException. That causal exception will show what the actual error is here.

**Comment by doodla** [comment]
Here's the full stacktrace.

```
FATAL EXCEPTION: main
Process: com.creditkarma.mobile.debug, PID: 7262
java.lang.RuntimeException: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class com.creditkarma.mobile.offers.ui.promowidget.PromoWidgetView
	at com.creditkarma.mobile.utils.CkLog.throwFirstExceptionIfDebug(CkLog.java:232)
	at com.creditkarma.mobile.utils.CkLog.wtf(CkLog.java:219)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapterUtils.onBindViewHolder(DelegatedViewAdapterUtils.java:23)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:50)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:16)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
	at android.view.View.measure(View.java:21783)
	at com.facebook.testing.screenshot.ViewHelpers.layoutInternal(ViewHelpers.java:79)
	at com.facebook.testing.screenshot.ViewHelpers.layout(ViewHelpers.java:68)
	at com.creditkarma.mobile.CkScreenshotTest.screenshotWithName(CkScreenshotTest.kt:77)
	at com.creditkarma.mobile.CkScreenshotTest.screenshotWithName$default(CkScreenshotTest.kt:63)
	at com.creditkarma.mobile.accounts.ui.overview.AccountsViewTest$captureAccountsViewRecyclerViewWithOffer$1.invoke(AccountsViewTest.kt:53)
	at com.creditkarma.mobile.accounts.ui.overview.AccountsViewTest$captureAccountsViewRecyclerViewWithOffer$1.invoke(AccountsViewTest.kt:26)
	at com.creditkarma.mobile.CkUiTest$sam$java_lang_Runnable$0.run(Unknown Source:2)
	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2086)
	at android.os.Handler.handleCallback(Handler.java:769)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class com.creditkarma.mobile.offers.ui.promowidget.PromoWidgetView
Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class com.creditkarma.mobile.offers.ui.promowidget.PromoWidgetView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:650)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:793)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:827)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at com.creditkarma.mobile.utils.ViewGroupKt.inflateView(ViewGroup.kt:19)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabOfferHeaderViewModel$ThreeTabOfferHeaderView.<init>(ThreeTabOfferHeaderViewModel.kt:180)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabOfferHeaderViewModel.<init>(ThreeTabOfferHeaderViewModel.kt:45)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabOfferHeaderViewModel$Companion.createAndBind(ThreeTabOfferHeaderViewModel.kt:165)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabBannerViewModel$HomeOfferBannerView.bind(ThreeTabBannerViewModel.kt:85)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabBannerViewModel.bindView(ThreeTabBannerViewModel.kt:35)
	at com.creditkarma.mobile.accounts.overview.AccountOfferViewModel$AccountOfferViewBindingHolder.bind(AccountOfferViewModel.kt:25)
	at com.creditkarma.mobile.accounts.overview.AccountOfferViewModel$AccountOfferViewBindingHolder.bind(AccountOfferViewModel.kt:18)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapterUtils.onBindViewHolder(DelegatedViewAdapterUtils.java:21)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:50)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:16)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
	at android.view.View.measure(View.java:21783)
	at com.facebook.testing.screenshot.ViewHelpers.layoutInternal(ViewHelpers.java:79)
	at com.facebook.testing.screenshot.ViewHelpers.layout(ViewHelpers.java:68)
	at com.creditkarma.mobile.CkScreenshotTest.screenshotWithName(CkScreenshotTest.kt:77)
	at com.creditkarma.mobile.CkScreenshotTest.screenshotWithName$default(CkScreenshotTest.kt:63)
	at com.creditkarma.mobile.accounts.ui.overview.AccountsViewTest$captureAccountsViewRecyclerViewWithOffer$1.invoke(AccountsViewTest.kt:53)
	at com.creditkarma.mobile.accounts.ui.overview.AccountsViewTest$captureAccountsViewRecyclerViewWithOffer$1.invoke(AccountsViewTest.kt:26)
	at com.creditkarma.mobile.CkUiTest$sam$java_lang_Runnable$0.run(Unknown Source:2)
	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2086)
	at android.os.Handler.handleCallback(Handler.java:769)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: android.content.res.Resources$NotFoundException: Drawable com.creditkarma.mobile.debug:id/action_bar_root with resource ID #0x7f090053
Caused by: android.content.res.Resources$NotFoundException: Resource "com.creditkarma.mobile.debug:id/action_bar_root" (7f090053) is not a Drawable (color or path): TypedValue{t=0x12/d=0x0 a=2 r=0x7f090053}
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:716)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:598)
	at android.content.res.Resources.getDrawableForDensity(Resources.java:876)
	at android.content.res.Resources.getDrawable(Resources.java:818)
	at android.content.Context.getDrawable(Context.java:605)
	at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:463)
	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:203)
	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
	at androidx.appcompat.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:753)
	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:196)
	at androidx.appcompat.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
	at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
	at com.google.android.material.resources.MaterialResources.getDrawable(MaterialResources.java:67)
	at com.google.android.material.chip.ChipDrawable.loadFromAttributes(ChipDrawable.java:396)
	at com.google.android.material.chip.ChipDrawable.createFromAttributes(ChipDrawable.java:278)
	at com.google.android.material.chip.Chip.<init>(Chip.java:172)
	at com.google.android.material.chip.Chip.<init>(Chip.java:165)
	at com.creditkarma.mobile.offers.ui.promowidget.PromoWidgetView.<init>(PromoWidgetView.kt:39)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at android.view.LayoutInflater.createView(LayoutInflater.java:650)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:793)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:733)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:827)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at com.creditkarma.mobile.utils.ViewGroupKt.inflateView(ViewGroup.kt:19)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabOfferHeaderViewModel$ThreeTabOfferHeaderView.<init>(ThreeTabOfferHeaderViewModel.kt:180)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabOfferHeaderViewModel.<init>(ThreeTabOfferHeaderViewModel.kt:45)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabOfferHeaderViewModel$Companion.createAndBind(ThreeTabOfferHeaderViewModel.kt:165)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabBannerViewModel$HomeOfferBannerView.bind(ThreeTabBannerViewModel.kt:85)
	at com.creditkarma.mobile.offers.ui.gqlhomeoffer.ThreeTabBannerViewModel.bindView(ThreeTabBannerViewModel.kt:35)
	at com.creditkarma.mobile.accounts.overview.AccountOfferViewModel$AccountOfferViewBindingHolder.bind(AccountOfferViewModel.kt:25)
	at com.creditkarma.mobile.accounts.overview.AccountOfferViewModel$AccountOfferViewBindingHolder.bind(AccountOfferViewModel.kt:18)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapterUtils.onBindViewHolder(DelegatedViewAdapterUtils.java:21)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:50)
	at com.creditkarma.mobile.ui.widget.recyclerview.DelegatedViewAdapter.onBindViewHolder(DelegatedViewAdapter.kt:16)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3336)
	at android.view.View.measure(View.java:21783)
	at com.facebook.testing.screenshot.ViewHelpers.layoutInternal(ViewHelpers.java:79)
	at com.facebook.testing.screenshot.ViewHelpers.layout(ViewHelpers.java:68)
	at com.creditkarma.mobile.CkScreenshotTest.screenshotWithName(CkScreenshotTest.kt:77)
	at com.creditkarma.mobile.CkScreenshotTest.screenshotWithName$default(CkScreenshotTest.kt:63)
	at com.creditkarma.mobile.accounts.ui.overview.AccountsViewTest$captureAccountsViewRecyclerViewWithOffer$1.invoke(AccountsViewTest.kt:53)
	at com.creditkarma.mobile.accounts.ui.overview.AccountsViewTest$captureAccountsViewRecyclerViewWithOffer$1.invoke(AccountsViewTest.kt:26)
	at com.creditkarma.mobile.CkUiTest$sam$java_lang_Runnable$0.run(Unknown Source:2)
	at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2086)
	at android.os.Handler.handleCallback(Handler.java:769)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by doodla** [comment]
Huh, looks like I never looked at the error properly. Looks like this is similar to #217.

**Comment by xiphirx** [comment]
Yup this is due to incorrectly bundling some support library artifacts. Closing in favor of #217
