### ISSUE TITLE
verifyScreenshotTest FAILED

### ISSUE THREAD

**Issue by sundetova** [facebook/screenshot-tests-for-android#252]
Hello, I faced error with failing verify task, when something changed in UI, and screenshot is not the same, verifyScreenshotTest failing with next error:
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':projectName:verify<flavor>ScreenshotTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at ...
Caused by: org.gradle.process.internal.ExecException: Process 'command 'python'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:409)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:38)
        at org.gradle.process.internal.DefaultExecActionFactory.exec(DefaultExecActionFactory.java:145)
        at org.gradle.api.internal.project.DefaultProject.exec(DefaultProject.java:1117)
        at com.facebook.testing.screenshot.build.PullScreenshotsTask.pullScreenshots(PullScreenshotsTask.kt:67)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
`
No diff report is generated. If screenshot is the same, tests are passed.

**Comment by xiphirx** [comment]
Verification doesn't currently generate a diff report, just tells you if certain screenshots changed.
