### ISSUE TITLE
The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant)

### ISSUE THREAD

**Issue by MohamedMedhat1998** [facebook/screenshot-tests-for-android#253]
## Explanation
I'm trying to use this library to implement screenshot-testing in my demo project  
Everything works fine before adding views from the `material` library.  
When I use any view from the material library, I face this error:  
```
android.view.InflateException: Binary XML file line #63: Error inflating class com.google.android.material.button.MaterialButton
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at com.andalus.playground.MainActivityTest.doScreenshot(MainActivityTest.kt:21)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at android.view.LayoutInflater.createView(LayoutInflater.java:607)
... 33 more
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
at com.google.android.material.internal.ThemeEnforcement.obtainStyledAttributes(ThemeEnforcement.java:76)
at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:200)
at com.google.android.material.button.MaterialButton.<init>(MaterialButton.java:191)
... 36 more
```
Although I use `Theme.MaterialComponents.Light.DarkActionBar` as the root style for my application.  
This is my `AppThem` style:  
```
<!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
    </style>
```
## Steps to reproduce
I tried to walk through [this doc](https://facebook.github.io/screenshot-tests-for-android/) but these are the exact steps I followed to implement screenshot-testing in my project:  

1. Added the classpath dependency (`build.gradle` project level)
```
  buildscript {
    // ...
    dependencies {
      // ...
      classpath 'com.facebook.testing.screenshot:plugin:0.12.0'
    }
  }
```
2. Applied the plugin of the library (`build.gradle` app level)
```
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'

apply plugin: 'com.facebook.testing.screenshot' //what I have added

android {
    compileSdkVersion 28
    buildToolsVersion "29.0.1"
    defaultConfig {
        //...
    }
//...
}
```
3. Added this dependency (`build.gradle` app level)  
```
dependencies {
   //...
   implementation 'com.facebook.testing.screenshot:layout-hierarchy-common:0.12.0'
}
```
4. Added the `WRITE_EXTERNAL_STORAGE` permission in `AndroidManiefest.xml`
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
5. And created a custom test runner  
```
public class MyTestRunner extends AndroidJUnitRunner {
  @Override
  public void onCreate(Bundle args) {
    ScreenshotRunner.onCreate(this, args);
    super.onCreate(args);
  }

  @Override
  public void finish(int resultCode, Bundle results) {
    ScreenshotRunner.onDestroy();
    super.finish(resultCode, results);
  }
}
```
6. Used it in `build.gradle` app level
```
defaultConfig {
    // ...
    testInstrumentationRunner "my.package.MyTestRunner" 
}
```
7. And finally wrote my test case
```
class MainActivityTest {

    @Test
    fun doScreenshot() {
        val context = InstrumentationRegistry.getInstrumentation().targetContext
        val view = LayoutInflater.from(context).inflate(R.layout.activity_main, null, false)
        ViewHelpers.setupView(view)
            .setExactWidthDp(300)
            .layout()
         Screenshot.snap(view)
            .record()
    }

}
```
8. My `activity_main.xml`
```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="#fffff0"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <androidx.viewpager.widget.ViewPager
        android:id="@+id/onboarding_slide_view_pager"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_marginBottom="0dp"
        android:overScrollMode="never"
        android:scrollbars="none"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <TextView
        android:id="@+id/skip_text_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginStart="20dp"
        android:layout_marginTop="8dp"
        android:layout_marginEnd="20dp"
        android:fontFamily="sans-serif-medium"
        android:gravity="center"
        android:minWidth="48dp"
        android:minHeight="48dp"
        android:text="skip"
        android:textAllCaps="true"
        android:textColor="#333333"
        android:textSize="14sp"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

    <LinearLayout
        android:id="@+id/slide_dots_container"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginBottom="4dp"
        android:gravity="center"
        android:minHeight="48dp"
        android:orientation="horizontal"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent" />

    <ImageView
        android:id="@+id/onboarding_fragment_next_image_view"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginEnd="12dp"
        android:gravity="center"
        android:minWidth="48dp"
        android:minHeight="48dp"
        android:padding="12dp"
        android:src="@android:drawable/stat_sys_phone_call_forward"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent" />

    <com.google.android.material.button.MaterialButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="material button"
        app:layout_constraintBottom_toTopOf="@+id/slide_dots_container"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
```
**Did I miss something?**
## Briefly 
Everything works well before using views from the `Material` library from Google. When I use it, the error appears.  
Please help!

**Comment by xiphirx** [comment]
`val context = InstrumentationRegistry.getInstrumentation().targetContext` 

This context is what you're inflating with and it likely doesn't have the correct theme applied. Either way, this isn't an issue with the library, but more your configuration.

**Comment by MohamedMedhat1998** [comment]
> 
> 
> `val context = InstrumentationRegistry.getInstrumentation().targetContext`
> 
> This context is what you're inflating with and it likely doesn't have the correct theme applied. Either way, this isn't an issue with the library, but more your configuration.

Thanks for the clarification!  

I could solve it, here is the change I made
```
val context = InstrumentationRegistry.getInstrumentation().targetContext
val themedContext = ContextThemeWrapper(context, R.style.AppTheme)
val view = LayoutInflater.from(themedContext).inflate(R.layout.activity_main, null, false)
```
