### ISSUE TITLE
Verify command fails due to missing build

### ISSUE THREAD

**Issue by MrXlebNick** [facebook/screenshot-tests-for-android#262]
Library version: 0.13.0

Task: verifyBrandProjectApiProdDebugAndroidTestScreenshotTest

Error message:
```

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
1 actionable task: 1 executed
        Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
        File "/home/xlebnick/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.13.0/db0cdddf8ac23f29bb95a7aff50bb68142ce5fea/plugin-0.13.0.jar/android_screenshot_tests/pull_screenshots.py", line 652, in <module>
        File "/home/xlebnick/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.13.0/db0cdddf8ac23f29bb95a7aff50bb68142ce5fea/plugin-0.13.0.jar/android_screenshot_tests/pull_screenshots.py", line 612, in main
File "/home/xlebnick/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.13.0/db0cdddf8ac23f29bb95a7aff50bb68142ce5fea/plugin-0.13.0.jar/android_screenshot_tests/aapt.py", line 57, in get_package
File "/home/xlebnick/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.13.0/db0cdddf8ac23f29bb95a7aff50bb68142ce5fea/plugin-0.13.0.jar/android_screenshot_tests/aapt.py", line 30, in _check_output
File "/home/xlebnick/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.13.0/db0cdddf8ac23f29bb95a7aff50bb68142ce5fea/plugin-0.13.0.jar/android_screenshot_tests/common.py", line 42, in check_output
File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'/home/xlebnick/Android/Sdk/build-tools/30.0.1/aapt', u'dump', u'badging', '/home/xlebnick/projects/project-android/ProjectMobile/build/outputs/apk/androidTest/brandProjectApiProd/debug/ProjectMobile-brandProject-apiProd-debug-androidTest.apk']' returned non-zero exit status 1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ProjectMobile:verifyBrandProjectApiProdDebugAndroidTestScreenshotTest'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
        12:23:56 AM: Task execution finished 'verifyBrandProjectApiProdDebugAndroidTestScreenshotTest'.

```

Executing `aapt` command manually in cli:
```
/home/xlebnick/Android/Sdk/build-tools/30.0.1/aapt dump badging /home/xlebnick/projects/project-android/ProjectMobile/build/outputs/apk/androidTest/brandProjectApiProd/debug/ProjectMobile-brandProject-apiProd-debug-androidTest.apk
asset W 09-02 00:48:10 26912 26912 Asset path /home/xlebnick/projects/project-android/ProjectMobile/build/outputs/apk/androidTest/brandProjectApiProd/debug/ProjectMobile-brandProject-apiProd-debug-androidTest.apk is neither a directory nor file (type=1).
ERROR: dump failed because assets could not be loaded
```

File `/home/xlebnick/projects/project-android/ProjectMobile/build/outputs/apk/androidTest/brandProjectApiProd/debug/ProjectMobile-brandProject-apiProd-debug-androidTest.apk` doesn't exist since the project was cleaned. I cleaned the project due to the very same error, thinking that probably the script doesn't see the file due to the file being generated with incorrect permissions or something.

**Comment by kotya341** [comment]
any update how to fix this?
