### ISSUE TITLE
FAILURE: Build failed with an exception. because of RuntimeError: ANDROID_SDK or ANDROID_HOME needs to be set

### ISSUE THREAD

**Issue by prashant-aakashedu-tech** [facebook/screenshot-tests-for-android#290]
gs
2 actionable tasks: 2 executed
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/aepl/.gradle/caches/jars-8/a3758272ae8be602ec3794dd2a2d61d9/plugin-0.14.0.jar/android_screenshot_tests/pull_screenshots.py", line 705, in <module>
  File "/home/aepl/.gradle/caches/jars-8/a3758272ae8be602ec3794dd2a2d61d9/plugin-0.14.0.jar/android_screenshot_tests/pull_screenshots.py", line 625, in main
  File "/home/aepl/.gradle/caches/jars-8/a3758272ae8be602ec3794dd2a2d61d9/plugin-0.14.0.jar/android_screenshot_tests/pull_screenshots.py", line 620, in setup_paths
  File "/home/aepl/.gradle/caches/jars-8/a3758272ae8be602ec3794dd2a2d61d9/plugin-0.14.0.jar/android_screenshot_tests/common.py", line 35, in get_android_sdk
RuntimeError: ANDROID_SDK or ANDROID_HOME needs to be set

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:pullDebugAndroidTestScreenshots'.
> Process 'command 'python'' finished with non-zero exit value 1

**Comment by BaloghTamas** [comment]
This is not an issue with the library itself, but with your configuration. Should be closed.

You need to set `ANDROID_SDK` or `ANDROID_HOME` environment variable to point to the Android SDK location. More info [here](https://askubuntu.com/questions/730/how-do-i-set-environment-variables)
