### ISSUE TITLE
App-Example screenshot doesn't build

### ISSUE THREAD

**Issue by victorvmp** [facebook/screenshot-tests-for-android#3]
I've try to launch the screenshot-tests-for-android example using ./gradlew screenshotTests --info and the gradle build fails with the following info trace.

:compileDebugAndroidTestNdk (Thread[main,5,main]) started.
:compileDebugAndroidTestNdk
Skipping task ':compileDebugAndroidTestNdk' as it has no source files.
:compileDebugAndroidTestNdk UP-TO-DATE
:compileDebugAndroidTestNdk (Thread[main,5,main]) completed. Took 0.007 secs.
:compileDebugAndroidTestSources (Thread[main,5,main]) started.
:compileDebugAndroidTestSources
Skipping task ':compileDebugAndroidTestSources' as it has no actions.
:compileDebugAndroidTestSources UP-TO-DATE
:compileDebugAndroidTestSources (Thread[main,5,main]) completed. Took 0.002 secs.
:preDexDebugAndroidTest (Thread[main,5,main]) started.
:preDexDebugAndroidTest
Skipping task ':preDexDebugAndroidTest' as it is up-to-date (took 0.01 secs).
:preDexDebugAndroidTest UP-TO-DATE
:preDexDebugAndroidTest (Thread[main,5,main]) completed. Took 0.012 secs.
:dexDebugAndroidTest (Thread[main,5,main]) started.
:dexDebugAndroidTest
Skipping task ':dexDebugAndroidTest' as it is up-to-date (took 0.011 secs).
:dexDebugAndroidTest UP-TO-DATE
:dexDebugAndroidTest (Thread[main,5,main]) completed. Took 0.015 secs.
:packageDebugAndroidTest (Thread[main,5,main]) started.
:packageDebugAndroidTest
Skipping task ':packageDebugAndroidTest' as it is up-to-date (took 0.012 secs).
:packageDebugAndroidTest UP-TO-DATE
:packageDebugAndroidTest (Thread[main,5,main]) completed. Took 0.015 secs.
:assembleDebugAndroidTest (Thread[main,5,main]) started.
:assembleDebugAndroidTest
Skipping task ':assembleDebugAndroidTest' as it has no actions.
:assembleDebugAndroidTest UP-TO-DATE
:assembleDebugAndroidTest (Thread[main,5,main]) completed. Took 0.001 secs.
:connectedDebugAndroidTest (Thread[main,5,main]) started.
:connectedDebugAndroidTest
Executing task ':connectedDebugAndroidTest' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
deleteDir(/Users/Victor/Proyects/git/screenshot-tests-for-android/examples/app-example/build/outputs/androidTest-results/connected) returned: true
deleteDir(/Users/Victor/Proyects/git/screenshot-tests-for-android/examples/app-example/build/outputs/code-coverage/connected) returned: true
Starting 3 tests on Nexus 4 - 4.4.2

com.facebook.testing.screenshot.SearchBarTest > testChinese[Nexus 4 - 4.4.2] SUCCESS 

com.facebook.testing.screenshot.SearchBarTest > testLongText[Nexus 4 - 4.4.2] SUCCESS 

com.facebook.testing.screenshot.SearchBarTest > testRendering[Nexus 4 - 4.4.2] SUCCESS 
deleteDir(/Users/Victor/Proyects/git/screenshot-tests-for-android/examples/app-example/build/reports/androidTests/connected) returned: true
:connectedDebugAndroidTest (Thread[main,5,main]) completed. Took 17.516 secs.
:connectedAndroidTest (Thread[main,5,main]) started.
:connectedAndroidTest
Skipping task ':connectedAndroidTest' as it has no actions.
:connectedAndroidTest (Thread[main,5,main]) completed. Took 0.001 secs.
:pullScreenshots (Thread[main,5,main]) started.
:pullScreenshots
Executing task ':pullScreenshots' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:pullScreenshots FAILED
:pullScreenshots (Thread[main,5,main]) completed. Took 0.034 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pullScreenshots'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 28.71 secs
Stopped 0 compiler daemon(s).

**Comment by tdrhq** [comment]
quick check, you mention ./gradlew, but I didn't add (I should though) a gradlew to this example. What version does gradle --version show?

Also, it looks like this crash is coming from the plugin code, can you run with --stacktrace so I can see what's NPE-ing? Thanks!

**Comment by victorvmp** [comment]
I'm using the default gradle wrapper that Android Studio add by default when a project without wrapper is imported.

Here the version of gradlew wrapper:

MacBook-Pro-de-Victor:app-example victor$ ./gradlew --version

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.10.3 x86_64

Here the full trace of ./gradlew screenshotTests --stacktrace

* What went wrong:
Execution failed for task ':pullScreenshots'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':pullScreenshots'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:33)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:130)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: java.lang.NullPointerException
        at org.gradle.process.internal.DefaultProcessForkOptions.getActualEnvironment(DefaultProcessForkOptions.java:75)
        at org.gradle.process.internal.AbstractExecHandleBuilder.build(AbstractExecHandleBuilder.java:124)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:28)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:154)
        at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:787)
        at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:783)
        at org.gradle.api.Project$exec$6.call(Unknown Source)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1.doCall(ScreenshotsPlugin.groovy:38)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 49 more


BUILD FAILED

Total time: 27.865 secs

Thank

**Comment by tdrhq** [comment]
I suspect this is an issue with the gradle version, I've added a gradlewrapper with version 2.6, can you check if this works?

**Comment by victorvmp** [comment]
I've tried to build the sample with gradle 2.6, but the output throw another different exception. Do you know why?

Here the full stacktrace:


MacBook-Pro-de-Victor:app-example victor$ ./gradlew --version

------------------------------------------------------------
Gradle 2.6
------------------------------------------------------------

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.10.3 x86_64

MacBook-Pro-de-Victor:app-example victor$ ./gradlew screenshotTests --stacktrace
Found jar file at /Users/victor/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.1/5cc1a6c29f9d96e2b4d52330c504efffed03770a/plugin-0.2.1.jar
:clearScreenshots
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:prepareDebugDependencies
:compileDebugAidl UP-TO-DATE
:compileDebugRenderscript UP-TO-DATE
:generateDebugBuildConfig UP-TO-DATE
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets UP-TO-DATE
:generateDebugResValues UP-TO-DATE
:generateDebugResources UP-TO-DATE
:mergeDebugResources UP-TO-DATE
:processDebugManifest UP-TO-DATE
:processDebugResources UP-TO-DATE
:generateDebugSources UP-TO-DATE
:processDebugJavaRes UP-TO-DATE
:compileDebugJavaWithJavac UP-TO-DATE
:compileDebugNdk UP-TO-DATE
:compileDebugSources UP-TO-DATE
:preDexDebug UP-TO-DATE
:dexDebug UP-TO-DATE
:validateDebugSigning
:packageDebug UP-TO-DATE
:zipalignDebug UP-TO-DATE
:assembleDebug UP-TO-DATE
:preDebugAndroidTestBuild UP-TO-DATE
:prepareDebugAndroidTestDependencies
:compileDebugAndroidTestAidl UP-TO-DATE
:processDebugAndroidTestManifest UP-TO-DATE
:compileDebugAndroidTestRenderscript UP-TO-DATE
:generateDebugAndroidTestBuildConfig UP-TO-DATE
:generateDebugAndroidTestAssets UP-TO-DATE
:mergeDebugAndroidTestAssets UP-TO-DATE
:generateDebugAndroidTestResValues UP-TO-DATE
:generateDebugAndroidTestResources UP-TO-DATE
:mergeDebugAndroidTestResources UP-TO-DATE
:processDebugAndroidTestResources UP-TO-DATE
:generateDebugAndroidTestSources UP-TO-DATE
:processDebugAndroidTestJavaRes UP-TO-DATE
:compileDebugAndroidTestJavaWithJavac UP-TO-DATE
:compileDebugAndroidTestNdk UP-TO-DATE
:compileDebugAndroidTestSources UP-TO-DATE
:preDexDebugAndroidTest UP-TO-DATE
:dexDebugAndroidTest UP-TO-DATE
:packageDebugAndroidTest UP-TO-DATE
:assembleDebugAndroidTest UP-TO-DATE
:connectedDebugAndroidTest
:connectedAndroidTest
:pullScreenshots
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/victor/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.1/5cc1a6c29f9d96e2b4d52330c504efffed03770a/plugin-0.2.1.jar/android_screenshot_tests/pull_screenshots.py", line 290, in <module>
  File "/Users/victor/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.1/5cc1a6c29f9d96e2b4d52330c504efffed03770a/plugin-0.2.1.jar/android_screenshot_tests/pull_screenshots.py", line 270, in main
  File "/Users/victor/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.1/5cc1a6c29f9d96e2b4d52330c504efffed03770a/plugin-0.2.1.jar/android_screenshot_tests/pull_screenshots.py", line 245, in get_package
  File "/Users/victor/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.1/5cc1a6c29f9d96e2b4d52330c504efffed03770a/plugin-0.2.1.jar/android_screenshot_tests/pull_screenshots.py", line 240, in get_aapt_bin
IndexError: list index out of range
:pullScreenshots FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pullScreenshots'.
> Process 'command 'python'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':pullScreenshots'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:158)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'python'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:366)
        at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:31)
        at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:165)
        at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:799)
        at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:795)
        at org.gradle.api.Project$exec$7.call(Unknown Source)
        at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1.doCall(ScreenshotsPlugin.groovy:38)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 60 more


BUILD FAILED

Total time: 28.715 secs

**Comment by tdrhq** [comment]
Looks like you don't have the android build tools installed? I should probably throw a more readable error in this case. Do you have a build-tools directory in your android-sdk directory?

**Comment by victorvmp** [comment]
Yes of course, I use the las build tools version 23.0.1

![image](https://cloud.githubusercontent.com/assets/5062911/10360898/da377566-6da4-11e5-9067-ce411d15ae10.png)

**Comment by tdrhq** [comment]
Platform? Windows, linux or Mac?

**Comment by victorvmp** [comment]
OS: Mac OS X 10.10.3 x86_64

**Comment by tdrhq** [comment]
can you create a gist with the output of

```
  $ find $ANDROID_SDK 
```
(or ANDROID_HOME), still trying to figure out what could be different about your directory structure.

**Comment by victorvmp** [comment]
The output of $ find $ANDROID_HOME is too big to be shared in gist. I've shared a file vía GoogleDrive.

Check the output in this file:

https://drive.google.com/file/d/0B_12pf9c-pJxTXlZRmx4M1FzQk0/view?usp=sharing

**Comment by tdrhq** [comment]
Everything looks good here, and should've worked. The python logic to find the aapt binary is a bit hacky, let me try replacing it with a less hacky version.

In the meantime, can you try running ./gradlew :plugin:pyTests in the main directory? It needs and emulator or device connected, and is most likely going to fail because of this error. But perhaps it'll provide me more useful information.

Also what's your python --version?

**Comment by tdrhq** [comment]
I've updated the aapt detection logic on master, can you pull and try again? (also :plugin:pyTests)

Remember to first install the plugin jar files to a local maven, I haven't pushed the updated version to maven central yet. Thanks!

**Comment by victorvmp** [comment]
The current python version:

MacBook-Pro-de-Victor:~ victor$ python --version
Python 2.7.6

Here the skacktrace of ./gradlew :plugin:pyTests in the main directory

https://gist.github.com/victorvmp/317af52d49f2e2de6bb3

After this i'm going to update the master, and try again

**Comment by tdrhq** [comment]
python version looks good, do a pip install mock an pip install pil (or maybe that's pillow) to make sure the tests can run appropriately

**Comment by tdrhq** [comment]
Any updates, did you try master?

**Comment by victorvmp** [comment]
After updated master, i've tried to run core and plugin test to verify that all is correct.

The :plugin:pyTests don't pass but :core:connectedAndroidTest yes. Before run test, I've launch installAll to add the artifacts to my local maven. Here the gist:

https://gist.github.com/victorvmp/9b138c356ef60d93670c

The screenshotTests tasks in example app still doesn't work. Here the trace.

https://gist.github.com/victorvmp/04bec6015b6ca507020c

**Comment by tdrhq** [comment]
woops, that's a stupid bug in my refactoring. The integration_tests caught the issue, so clearly I didn't run the test before pushing it.

I've updated it with a fix, please try again! (cf01da7c258619b37484c6f5b206c55b31bd0d48)

**Comment by victorvmp** [comment]
Doesn't work. I've updated the latests gists. Check it here:

https://gist.github.com/victorvmp/9b138c356ef60d93670c

https://gist.github.com/victorvmp/04bec6015b6ca507020c

**Comment by tdrhq** [comment]
By any chance have you set your ANDROID_SDK environment variable to "null" (the explicit null string). That's the only explanation I can get from the logs. You mentioned you have an ANDROID_HOME, but the script checks for ANDROID_SDK first.

If so, try `unset ANDROID_SDK` and try this again.

**Comment by victorvmp** [comment]
I've added and ANDROID_SDK environment variable:

https://gist.github.com/victorvmp/04795ae9741a745795e6

The mock and pillow are correctly installed:

https://gist.github.com/victorvmp/8517d2a35c3122843bf1

I've install repo to local using installAll:

https://gist.github.com/victorvmp/b696418eb76e1b2a72b4

But unfortunately that stuff isn't enough to pass :plugin:pyTests, here the stacktrace:

https://gist.github.com/victorvmp/1fc9bf1ec1610e27130b

Also example app test doesn't run, here the stacktrace:

https://gist.github.com/victorvmp/409c9fa8f3d191937928

I don't know what I'm doing wrong, do you have some recommendations to fix this?

**Comment by tdrhq** [comment]
This new error looks similar to #4 . I think I have a fix in master, can you try master again?

**Comment by tdrhq** [comment]
Should be fixed in 5ca87aa9ce9d0b9ff851b16a6902e94f7f6a048e, if you can verify the fix I'll bump the version on maven central

**Comment by tdrhq** [comment]
Okay this should work now either in master or in the bumped version of 0.2.3

**Comment by victorvmp** [comment]
Yes! now the sample app works! thank!
