### ISSUE TITLE
Fail to execute runDebugAndroidTestScreenshotTest due to syntax error

### ISSUE THREAD

**Issue by Quang0309** [facebook/screenshot-tests-for-android#303]
> Task :app:runDebugAndroidTestScreenshotTest FAILED
[-m, android_screenshot_tests.pull_screenshots, --apk, /Users/nguyentnq/sealabs/ScreenShotDemo/app/build/intermediates/apk/androidTest/debug/app-debug-androidTest.apk, --test-run-id, 3093337c-50b3-42fc-840a-c89c8b02656a, --temp-dir, /Users/nguyentnq/sealabs/ScreenShotDemo/app/build/screenshotsDebugAndroidTest]
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 119, in _get_module_details
    code = loader.get_code(mod_name)
  File "/Users/nguyentnq/.gradle/caches/jars-9/c0e3396506bdc4bbb1c7955ef2d0f623/plugin-0.15.0.jar/android_screenshot_tests/pull_screenshots.py", line 57
    file=sys.stderr,
        ^
SyntaxError: invalid syntax

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runDebugAndroidTestScreenshotTest'.
> Process 'command 'python'' finished with non-zero exit value 1

**Comment by RubenMH** [comment]
I have the same problem. @Quang0309 Do you find a solution?
