### ISSUE TITLE
NullPointer on make screenshot if use anotation tests

### ISSUE THREAD

**Issue by punksta** [facebook/screenshot-tests-for-android#37]
I have 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Instrumentation.getContext()' on a null object reference
at com.facebook.testing.screenshot.internal.ScreenshotImpl.getInstance(ScreenshotImpl.java:338)
at com.facebook.testing.screenshot.Screenshot.snapActivity(Screenshot.java:45)
at com.mobium.reference.activity.Util.takeScreenshot(Util.java:32)
at com.mobium.reference.activity.SimpleActicityTest.lambda$testLeftMenuTest$1(SimpleActicityTest.java:52)
at com.mobium.reference.activity.SimpleActicityTest.access$lambda$0(SimpleActicityTest.java)
at com.mobium.reference.activity.SimpleActicityTest$$Lambda$1.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5549)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
```
when I run test:
```
@LargeTest
@RunWith(AndroidJUnit4.class)
public class SimpleActicityTest {


@Rule
public ActivityTestRule<MainActivity> activityActivityTestRule =
        new ActivityTestRule<>(MainActivity.class);

@Test
public void testActivity() throws Exception {
    Activity a = activityActivityTestRule.getActivity();
    Screenshot.snapActivity(activity).setName("s1").record();
}
}
```
`ScreenshotImpl getInstance() creates Registry and take public field instrumentation, but there are not instrumentation initializations in Registry constructor.

**Comment by tdrhq** [comment]
Screenshot tests requires a custom instrumentation, if you use ScreenshotTestRunner that ships with the library, then you won't get JUnit4 support that comes with android-support-lib.

The way to fix this, is to use a override a custom Instrumentation from AndroidJUnitRunner, and make sure you call ScreenshotRunner.onCreate/onDestroy from appropriate locations. 

Let me know if this fixes the issue

**Comment by punksta** [comment]
Thanks!
