### ISSUE TITLE
Can't execute pullScreenshots

### ISSUE THREAD

**Issue by kylannjohnson** [facebook/screenshot-tests-for-android#4]
On a fresh project, running one test, one screenshot, with Gradle plugin 2.6. I get the following stack trace

```
 What went wrong:
Execution failed for task ':app:pullScreenshots'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:pullScreenshots'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.NullPointerException
	at org.gradle.process.internal.DefaultProcessForkOptions.getActualEnvironment(DefaultProcessForkOptions.java:75)
	at org.gradle.process.internal.AbstractExecHandleBuilder.build(AbstractExecHandleBuilder.java:124)
	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:28)
	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:154)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:787)
	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:783)
	at org.gradle.api.Project$exec$8.call(Unknown Source)
	at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1.doCall(ScreenshotsPlugin.groovy:38)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 49 more
```

**Comment by kylannjohnson** [comment]
Same stack trace but with Lifecycle debug traces around it

```
5:53:21.660 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:connectedAndroidTest (Thread[main,5,main]) completed. Took 0.001 secs.
15:53:21.660 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:pullScreenshots (Thread[main,5,main]) started.
15:53:21.660 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:pullScreenshots
15:53:21.660 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':app:pullScreenshots'
15:53:21.661 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':app:pullScreenshots' is up-to-date
15:53:21.661 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':app:pullScreenshots' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
15:53:21.661 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:pullScreenshots'.
15:53:21.675 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:pullScreenshots'
15:53:21.675 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:pullScreenshots FAILED
15:53:21.676 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:pullScreenshots (Thread[main,5,main]) completed. Took 0.016 secs.
15:53:21.688 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 5.207 secs, idle: 0.036 secs
15:53:21.694 [ERROR] [org.gradle.BuildExceptionReporter]
15:53:21.695 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:53:21.695 [ERROR] [org.gradle.BuildExceptionReporter]
15:53:21.696 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:53:21.696 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':app:pullScreenshots'.
15:53:21.696 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NullPointerException (no error message)
15:53:21.696 [ERROR] [org.gradle.BuildExceptionReporter]
15:53:21.697 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
15:53:21.697 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:pullScreenshots'.
15:53:21.697 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
15:53:21.698 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
15:53:21.698 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
15:53:21.698 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
15:53:21.698 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
15:53:21.698 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
15:53:21.699 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
15:53:21.699 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
15:53:21.699 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
15:53:21.699 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
15:53:21.699 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
15:53:21.700 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
15:53:21.700 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
15:53:21.700 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
15:53:21.700 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
15:53:21.700 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
15:53:21.700 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:53:21.701 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
15:53:21.701 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
15:53:21.701 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
15:53:21.701 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
15:53:21.701 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
15:53:21.701 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
15:53:21.701 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
15:53:21.702 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
15:53:21.702 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
15:53:21.702 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
15:53:21.702 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:53:21.702 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
15:53:21.702 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
15:53:21.703 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
15:53:21.703 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
15:53:21.703 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
15:53:21.703 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
15:53:21.703 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
15:53:21.703 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
15:53:21.703 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
15:53:21.704 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
15:53:21.704 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
15:53:21.704 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
15:53:21.704 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
15:53:21.704 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
15:53:21.704 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
15:53:21.704 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultProcessForkOptions.getActualEnvironment(DefaultProcessForkOptions.java:75)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.AbstractExecHandleBuilder.build(AbstractExecHandleBuilder.java:124)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.process.internal.DefaultExecAction.execute(DefaultExecAction.java:28)
15:53:21.705 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.file.DefaultFileOperations.exec(DefaultFileOperations.java:154)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:787)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.exec(AbstractProject.java:783)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.Project$exec$7.call(Unknown Source)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.facebook.testing.screenshot.build.ScreenshotsPlugin$_apply_closure1.doCall(ScreenshotsPlugin.groovy:38)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:558)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:539)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
15:53:21.706 [ERROR] [org.gradle.BuildExceptionReporter] 	... 49 more
15:53:21.707 [ERROR] [org.gradle.BuildExceptionReporter]
15:53:21.707 [LIFECYCLE] [org.gradle.BuildResultLogger]
15:53:21.707 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
15:53:21.707 [LIFECYCLE] [org.gradle.BuildResultLogger]
15:53:21.707 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 9.376 secs
```

**Comment by kylannjohnson** [comment]
I attempted to execute your example with the latest on master and got the snippet below when starting the pull_screenshots module

I can execute this in term, it's just the environment not finding the device ``` error: device 'null' not found ```

```
python -m android_screenshot_tests.pull_screenshots --apk /Users/knjohn/code/screenshot-tests-for-android/examples/app-example/build/outputs/apk/app-example-debug-androidTest-unaligned.apk
```

```
Skipping task ':connectedAndroidTest' as it has no actions.
:connectedAndroidTest (Thread[main,5,main]) completed. Took 0.001 secs.
:pullScreenshots (Thread[main,5,main]) started.
:pullScreenshots
Executing task ':pullScreenshots' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'python''. Working directory: /Users/knjohn/code/screenshot-tests-for-android/examples/app-example Command: python -m android_screenshot_tests.pull_screenshots --apk /Users/knjohn/code/screenshot-tests-for-android/examples/app-example/build/outputs/apk/app-example-debug-androidTest-unaligned.apk
Successfully started process 'command 'python''
error: device 'null' not found
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 253, in <module>
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 250, in main
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 191, in pull_screenshots
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 172, in pull_filtered
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 144, in pull_metadata
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/simple_puller.py", line 27, in remote_file_exists
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'adb', u'shell', u'test -e /sdcard/screenshots/com.facebook.testing.screenshot.examples.test/screenshots-default/metadata.xml && echo EXISTS']' returned non-zero exit status 255
:pullScreenshots FAILED
:pullScreenshots (Thread[main,5,main]) completed. Took 0.098 secs.
```

**Comment by tdrhq** [comment]
Quick sanity checks for debugging.. do you have a device connected, do you have *more than one* device connected? If not, is it an emulator or device or genymotion? Android version?

**Comment by tdrhq** [comment]
I think the reason for this is that adb is not on your PATH. But I'm not 100% sure. Can you try installing from master? I've updated it with what I think is a fix. (Not uploaded the fix to maven central yet)

**Comment by kylannjohnson** [comment]
Yes, my normal setup is a Nexus 6 API 22 running on genymotion.  I'm fairly certain I only had one device active at one time.  I did try to run on an actual Nexus 6 (genymotion was stopped), but the same result happened.    Both devices are API 22, my buildToolsVersion is 23.0.1, my python version is 2.7.10

Here's my gradle setup:

```
------------------------------------------------------------
Gradle 2.6
------------------------------------------------------------

Build time:   2015-08-10 13:15:06 UTC
Build number: none
Revision:     233bbf8e47c82f72cb898b3e0a96b85d0aad166e

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_51 (Oracle Corporation 25.51-b03)
OS:           Mac OS X 10.10.5 x86_64
```

**Comment by kylannjohnson** [comment]
I considered the adb problem, but I believe it's on my PATH
```
± % adb -version 
Android Debug Bridge version 1.0.32
Revision eac51f2bb6a8-android
```

Trace:
```
Executing task ':pullScreenshots' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Starting process 'command 'python''. Working directory: /Users/knjohn/code/screenshot-tests-for-android/examples/app-example Command: python -m android_screenshot_tests.pull_screenshots --apk /Users/knjohn/code/screenshot-tests-for-android/examples/app-example/build/outputs/apk/app-example-debug-androidTest-unaligned.apk
Successfully started process 'command 'python''
error: device 'null' not found
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 253, in <module>
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 250, in main
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 191, in pull_screenshots
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 172, in pull_filtered
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/pull_screenshots.py", line 144, in pull_metadata
  File "/Users/knjohn/.gradle/caches/modules-2/files-2.1/com.facebook.testing.screenshot/plugin/0.2.2/ff11b539a14ce187a3ff7a8f89fc127fa869deed/plugin-0.2.2.jar/android_screenshot_tests/simple_puller.py", line 27, in remote_file_exists
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'adb', u'shell', u'test -e /sdcard/screenshots/com.facebook.testing.screenshot.examples.test/screenshots-default/metadata.xml && echo EXISTS']' returned non-zero exit status 255
:pullScreenshots FAILED
:pullScreenshots (Thread[main,5,main]) completed. Took 0.095 secs.
```

**Comment by tdrhq** [comment]
ah, I know the issue. This line is causing the problem: https://github.com/facebook/screenshot-tests-for-android/blob/master/plugin/src/main/groovy/com/facebook/testing/screenshot/build/ScreenshotsPlugin.groovy#L39

Fix coming up

**Comment by tdrhq** [comment]
Should be fixed in 5ca87aa9ce9d0b9ff851b16a6902e94f7f6a048e, if you can verify the fix I'll bump the version on maven central

**Comment by kylannjohnson** [comment]
I think that did it!  Thanks for your help.  I'll try to integrate it into my app now, so I'll let you know if i find anything else.

```
:assembleDebugAndroidTest
:connectedDebugAndroidTest
:connectedAndroidTest
:pullScreenshots



Found 3 screenshots
Open the following url in a browser to view the results:
  file:///var/folders/7r/lg_y56q16md4p92q9gllwjv4z2dxbr/T/screenshots2k1Z6h/index.html



:screenshotTests

BUILD SUCCESSFUL

Total time: 16.137 secs
```

**Comment by tdrhq** [comment]
Thanks for verifying! I have bumped the version on maven central
