### ISSUE TITLE
runTests[MI 3C - 6.0.1] FAILED - can not install apk

### ISSUE THREAD

**Issue by longerian** [facebook/screenshot-tests-for-android#45]
execute `gradle screenshotTests `, show error as below:

```
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Parallel execution is an incubating feature.
Incremental java compilation is an incubating feature.
Probe disabled for demoDebug
Probe disabled for demoRelease
Probe disabled for fullDebug
Probe disabled for fullRelease
:clearScreenshots
:preBuild UP-TO-DATE
:preFullDebugBuild UP-TO-DATE
:checkFullDebugManifest
:preDemoDebugBuild UP-TO-DATE
:preDemoReleaseBuild UP-TO-DATE
:preFullReleaseBuild UP-TO-DATE
:prepareComAndroidSupportCardviewV72400Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72400Library UP-TO-DATE
:prepareComAndroidSupportSupportV42400Library UP-TO-DATE
:prepareOrgLucasrProbeProbe013Library UP-TO-DATE
:prepareFullDebugDependencies
:compileFullDebugAidl UP-TO-DATE
:compileFullDebugRenderscript UP-TO-DATE
:generateFullDebugBuildConfig UP-TO-DATE
:mergeFullDebugShaders UP-TO-DATE
:compileFullDebugShaders UP-TO-DATE
:generateFullDebugAssets UP-TO-DATE
:mergeFullDebugAssets UP-TO-DATE
:generateFullDebugResValues UP-TO-DATE
:generateFullDebugResources UP-TO-DATE
:mergeFullDebugResources
:processFullDebugManifest UP-TO-DATE
:processFullDebugResources
:generateFullDebugSources
:incrementalFullDebugJavaCompilationSafeguard UP-TO-DATE
:compileFullDebugJavaWithJavac
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
:compileFullDebugNdk UP-TO-DATE
:compileFullDebugSources
:prePackageMarkerForFullDebug
:transformClassesWithDexForFullDebug
Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
:mergeFullDebugJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForFullDebug UP-TO-DATE
:processFullDebugJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForFullDebug UP-TO-DATE
:validateDebugSigning
:packageFullDebug
:zipalignFullDebug
:assembleFullDebug
:preFullDebugAndroidTestBuild UP-TO-DATE
:prepareFullDebugAndroidTestDependencies
:compileFullDebugAndroidTestAidl UP-TO-DATE
:processFullDebugAndroidTestManifest UP-TO-DATE
:compileFullDebugAndroidTestRenderscript UP-TO-DATE
:generateFullDebugAndroidTestBuildConfig UP-TO-DATE
:mergeFullDebugAndroidTestShaders UP-TO-DATE
:compileFullDebugAndroidTestShaders UP-TO-DATE
:generateFullDebugAndroidTestAssets UP-TO-DATE
:mergeFullDebugAndroidTestAssets UP-TO-DATE
:generateFullDebugAndroidTestResValues UP-TO-DATE
:generateFullDebugAndroidTestResources UP-TO-DATE
:mergeFullDebugAndroidTestResources UP-TO-DATE
:processFullDebugAndroidTestResources UP-TO-DATE
:generateFullDebugAndroidTestSources UP-TO-DATE
:incrementalFullDebugAndroidTestJavaCompilationSafeguard UP-TO-DATE
:compileFullDebugAndroidTestJavaWithJavac UP-TO-DATE
:compileFullDebugAndroidTestNdk UP-TO-DATE
:compileFullDebugAndroidTestSources UP-TO-DATE
:prePackageMarkerForFullDebugAndroidTest
:transformClassesWithDexForFullDebugAndroidTest UP-TO-DATE
:mergeFullDebugAndroidTestJniLibFolders UP-TO-DATE
:transformNative_libsWithMergeJniLibsForFullDebugAndroidTest UP-TO-DATE
:processFullDebugAndroidTestJavaRes UP-TO-DATE
:transformResourcesWithMergeJavaResForFullDebugAndroidTest UP-TO-DATE
:packageFullDebugAndroidTest UP-TO-DATE
:assembleFullDebugAndroidTest UP-TO-DATE
:connectedFullDebugAndroidTest
Unable to install /Users/longerian/Documents/android-workspace/longerian/ABCAndroid/build/outputs/apk/ABCAndroid-full-debug.apk
com.android.ddmlib.InstallException: Failed to establish session
        at com.android.ddmlib.SplitApkInstaller.install(SplitApkInstaller.java:66)
        at com.android.ddmlib.Device.installPackages(Device.java:901)
        at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:119)
        at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:121)
        at com.android.builder.internal.testing.SimpleTestCallable.call(SimpleTestCallable.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

com.android.builder.testing.ConnectedDevice > runTests[MI 3C - 6.0.1] FAILED 
        com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: Failed to establish session
                at com.android.builder.testing.ConnectedDevice.installPackages(ConnectedDevice.java:129)

FAILURE: Build failed with an exception.

* What went wrong:
Could not receive a message from the daemon.

```

dev env:

```
systemProp.compileSdkVersion=23
systemProp.buildToolsVersion=23.0.1

    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.0'
        classpath 'org.lucasr.probe:gradle-plugin:0.1.3'
        classpath 'com.facebook.testing.screenshot:plugin:0.4.2'
    }
```

+ mac os
+

**Comment by tdrhq** [comment]
this seems unrelated to screenshot-tests, and seems like it's coming from the android gradle plugin. Try restarting adb server, different device, etc. Make sure you can run `gradle :connectedDebugAndroidTest` which is what screenshotTests uses as a dependency.

**Comment by longerian** [comment]
thanks, it's caused by MI device, see this issue https://github.com/facebook/react-native/issues/6499
