### ISSUE TITLE
Error inflating class

### ISSUE THREAD

**Issue by just-kip** [facebook/screenshot-tests-for-android#57]
Some custom views throws android.view.InflateException
For example

```
    @Test
    public void testDoScreenshot() throws Exception {
        Context appContext = InstrumentationRegistry.getTargetContext();
        LayoutInflater inflater = LayoutInflater.from(appContext);

        View view = inflater.inflate(R.layout.activity_main, null, false);

        SwipeLayout swipeLayout  = (SwipeLayout) view.findViewById(R.id.swipeLayout);

        ViewHelpers.setupView(swipeLayout)
                .setExactWidthDp(300)
                .layout();

        Screenshot.snap(swipeLayout)
                .record();
    }
```

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.daimajia.swipe.SwipeLayout
        android:id="@+id/swipeLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <TextView
            android:text="Hello World"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />

    </com.daimajia.swipe.SwipeLayout>

</LinearLayout>
```

```
android.view.InflateException: Binary XML file line #6: Error inflating class com.daimajia.swipe.SwipeLayout
at android.view.LayoutInflater.createView(LayoutInflater.java:640)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
at recyclerview.research.funbox.io.ScreenTest.testDoScreenshot(ScreenTest.java:53)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1873)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at android.view.LayoutInflater.createView(LayoutInflater.java:614)
... 35 more
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:200)
at android.os.Handler.<init>(Handler.java:114)
at android.view.GestureDetector$GestureHandler.<init>(GestureDetector.java:258)
at android.view.GestureDetector.<init>(GestureDetector.java:363)
at android.view.GestureDetector.<init>(GestureDetector.java:344)
at com.daimajia.swipe.SwipeLayout.<init>(SwipeLayout.java:1073)
at com.daimajia.swipe.SwipeLayout.<init>(SwipeLayout.java:79)
... 38 more
```

**Comment by tdrhq** [comment]
Right, so looks like you're using a view that requires you to be on the UI thread. You can use Instrumentation.runOnMainSync() (or use the @UiThreadRule in JUnit3 tests) to make the test run on the UI thread
