### ISSUE TITLE
Can't take a screenshot, since this view is not measured. when using snapActivity()

### ISSUE THREAD

**Issue by chris-gunawardena** [facebook/screenshot-tests-for-android#68]
When just using `Screenshot.snapActivity(mActivityTestRule.getActivity()).record();` as per the [example](https://github.com/facebook/screenshot-tests-for-android/blob/master/examples/app-example-androidjunitrunner/app/src/androidTest/java/com/example/screenshots/MainActivityTest.java) I am seeing the "Can't take a screenshot, since this view is not measured." message. Any ideas what could be wrong?

Full message:
`
java.lang.RuntimeException: java.lang.RuntimeException: Can't take a screenshot, since this view is not measured
at com.facebook.testing.screenshot.internal.ScreenshotImpl.runCallableOnUiThread(ScreenshotImpl.java:323)
at com.facebook.testing.screenshot.internal.ScreenshotImpl.storeBitmap(ScreenshotImpl.java:128)
at com.facebook.testing.screenshot.internal.ScreenshotImpl.record(ScreenshotImpl.java:249)
at com.facebook.testing.screenshot.internal.RecordBuilderImpl.record(RecordBuilderImpl.java:150)
at com.ibm.jumbo.test.mocked.modules.ui.fragment.products.MyProductsTabFragmentTest.should_show_three_my_products(MyProductsTabFragmentTest.java:193)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at com.github.tomakehurst.wiremock.junit.WireMockRule$1.evaluate(WireMockRule.java:72)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)
Caused by: java.lang.RuntimeException: Can't take a screenshot, since this view is not measured
at com.facebook.testing.screenshot.internal.ScreenshotImpl.storeBitmap(ScreenshotImpl.java:141)
at com.facebook.testing.screenshot.internal.ScreenshotImpl.access$000(ScreenshotImpl.java:43)
at com.facebook.testing.screenshot.internal.ScreenshotImpl$2.call(ScreenshotImpl.java:131)
at com.facebook.testing.screenshot.internal.ScreenshotImpl$2.call(ScreenshotImpl.java:128)
at com.facebook.testing.screenshot.internal.ScreenshotImpl$3.run(ScreenshotImpl.java:305)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

**Comment by tdrhq** [comment]
uggh, looks like snapActivity() isn't calling waitForIdleSync(). Can you try calling InstrumentationRegistry.getInstrumentation().waitForIdleSync() before calling snapActivity()? If that works I'll modify the code appropriately

**Comment by chris-gunawardena** [comment]
Thanks unfortunately it didn't work, still getting the same error.
```
    @Test
    public void screenshot_test() throws Exception {
        InstrumentationRegistry.getInstrumentation().waitForIdleSync();
        Screenshot.snapActivity(mActivityTestRule.getActivity()).record();
    }
```
I run it using the following command: 
❯  ./gradlew clean recordMode screenshotTests  -Pandroid.testInstrumentationRunnerArguments.class=com.ibm.jumbo.test.mocked.modules.ui.fragment.products.MyProductsTabFragmentTest#screenshot_test

I've tried python version 2.7 & 3.4, the gradle version is 2.3

**Comment by tdrhq** [comment]
one more thing, can you call mActivityTestRule.getActivity() before waitForIdleSync() too? I want to make sure the activity is completely created an stable before you snap the view.

**Comment by chris-gunawardena** [comment]
Thank you! It didn't fix the issue but did point me in the right direction. This app uses one activity as an entry point to load stuff, all the test cases start with this activity which mActivityTestRule.getActivity() was returning which happens to be an empty activity. This also explains why I was getting transparent screenshots in #69 

Fix was to get the 'current' activity and pass it to `Screenshot.snapActivity(Utils.getCurrentActivity()).record();`

```
    public static Activity getCurrentActivity() {
        final Activity[] activity = new Activity[1];
        onView(isRoot()).check(new ViewAssertion() {
            @Override
            public void check(View view, NoMatchingViewException noViewFoundException) {
                activity[0] = (Activity) view.findViewById(android.R.id.content).getContext();
            }
        });
        return activity[0];
    }
```

**Comment by palimad** [comment]
could you please post isRoot() method?
