### ISSUE TITLE
TestSimplePuller.test_file_exists fails for API 24

### ISSUE THREAD

**Issue by marcinkunert** [facebook/screenshot-tests-for-android#83]
Tested with

- emulator API 24 and 25
- OSX Sierra
- Python 2.7.10

Info: Works fine with API 22.
```
ERROR: test_file_exists (android_screenshot_tests.test_simple_puller.TestSimplePuller)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marcin/Projects/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/test_simple_puller.py", line 50, in test_file_exists
    self.assertFalse(self.puller.remote_file_exists("/sdcard/sdfdsfdf"))
  File "/Users/marcin/Projects/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/simple_puller.py", line 29, in remote_file_exists
    "test -e %s && echo EXISTS" % src])

  File "/Users/marcin/Projects/screenshot-tests-for-android/plugin/src/py/android_screenshot_tests/common.py", line 36, in check_output
    return subprocess.check_output(args, **kwargs).decode('utf-8')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/Users/marcin/Library/Android/sdk/platform-tools/adb', u'shell', u'test -e /sdcard/sdfdsfdf && echo EXISTS']' returned non-zero exit status 1
```

**Comment by HannahMitt** [comment]
It looks like this didn't make it into 0.4.3. Is 0.4.4 on the horizon?

**Comment by tdrhq** [comment]
There were a few issues with some integration tests, but apart from that I just create new versions every now and then.. there's no set release schedule right now. So if this is a big issue, I can release a new version (but after making those tests pass again)

**Comment by HannahMitt** [comment]
I turned it out it mattered less than I thought, so no worries. Thanks @tdrhq
